import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

export const metadata: Metadata = {
  title: "Pub-Z - Taverna Medieval",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col antialiased">
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
